Logging
urfu-2016/team4 pull request #103
Opened 2017-05-09 17:44 UTC by Zeace

2017-05-09 18:52 UTC, AtnesNess requested changes
Что то не понятно как это будет работать на клиентском js

2017-05-09 18:52 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.js
>  let publishInput = block.querySelector('.publish');
хм а как  логи клиентского js попадут к нам на сервер?

2017-05-09 18:52 UTC, AtnesNess commented on src/middlewares/intel-logger.js
> +let intel = require('intel');
А это файл заем? откуда он запускается?

2017-05-10 07:47 UTC, TrefilovAnd commented on src/middlewares/intel-logger.js
> +let intel = require('intel');
я тоже не нашел такой модуль в инете)

2017-05-10 07:48 UTC, AtnesNess commented on src/middlewares/intel-logger.js
> +let intel = require('intel');
Я имел ввиду сам intel-logger.js :D он ни от куда не запускается и вообще не ясно че делает

2017-05-10 11:30 UTC, AtnesNess requested changes
Выпилить левые файлы
Разобраться с module.exports и exports.property

2017-05-10 11:30 UTC, AtnesNess commented on README.md
> -# team4. "Фотоквест"
ридми выпили из ПР

2017-05-10 11:30 UTC, AtnesNess commented on .gitignore
> -.idea/
это тоже выпили

2017-05-10 11:30 UTC, AtnesNess commented on src/middlewares/intel-logger.js
> +intel.basicConfig({
как это работает? ты даже не экспортируешь его :D

2017-05-10 11:30 UTC, AtnesNess commented on src/middlewares/middlewares.js
> +intel.config(require('./intel-logger'));
magic

2017-05-10 13:17 UTC, AtnesNess approved these changes

2017-05-11 16:38 UTC, TrefilovAnd approved these changes

2017-05-11 17:30 UTC, merged