quest removing
urfu-2016/team4 pull request #114
Opened 2017-05-11 17:55 UTC by TrefilovAnd

Юзеры могут удалять свои квесты:
- в редакторе, если квест не опубликован
- в описании квеста, если опубликован

При удалении:
- удаляются фотки
- удаляется квест у юзера

2017-05-11 18:15 UTC, AtnesNess requested changes

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                console.log(result);
логи нужно убрать

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                return res.status(500).send({message: 'Error'});
добавить intel логи

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                    if (!err) {
а если err? или если !user?
intel logs

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                                cacheTools.clearCache('my-quests-created', user);
молодец что предусмотрел, но нужно еще почистить кэш самого квеста.
cacheTools.clearCache('quest-' + quest.id);

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                        user.save();
тут операция может не увенчаться успехом, и нужно бы тоже чистить кэш для юззера
cacheTools.clearCache('user', user);

2017-05-11 18:15 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                User.findById(quest.author, (err, user) => {
А что будет с юзерами которые что-то уже отметили в твоем квесте?

2017-05-11 18:15 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.js
> +    let removeURL = window.location.pathname
извращения не знают границ :D
но вообще пойдет)
Хотя я бы просто внизу еще одну формочку запилил с ругим рутом и submit input "удалить"
Как это сделано в quest-description-page

2017-05-12 17:54 UTC, TrefilovAnd commented on src/apps/quests/controllers.js
> +                        user.save();
ты про save()?

2017-05-12 20:45 UTC, AtnesNess requested changes
Супер, осталось разобраться с асинхронностью и ошибками

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                user.save();
Тут нужно чистить кэш юзера

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +            deleteQuestFromUsers(quest);
Это асинхронная операция, что если произойдет ошибка? У юзеров останется этот квест, а в базе его не будет

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +            photoTools.deletePhotos(quest.photos, () => {
Ошибки нужно обрабатывать. deletePhotos ее вернет в случае ошибки

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                    user.save();
кэш, и проверка на ошибки

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                        cacheTools.clearCache('user', user);
Лучше его чистить после успешного сохранения юзера

2017-05-12 20:45 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +                user.save();
Нужно в этой функции либо promise.all вернуть в который переданы все удаления квеста у юзеров, либо реализовать по типу savePhotos (https://github.com/urfu-2016/team4/pull/116), так как нужно дождаться завершения этой функции прежде чем удалять сам квест

2017-05-13 17:00 UTC, Zeace approved these changes

2017-05-13 17:06 UTC, AtnesNess approved these changes

2017-05-13 17:54 UTC, merged