указание геолокации(без валидации)
urfu-2016/team4 pull request #117
Opened 2017-05-12 20:08 UTC by Sergey-Ubogov

2017-05-12 20:12 UTC, Sergey-Ubogov commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +    let photoLocation = questPhoto.querySelector('.photo-location');
дублирование кода

2017-05-12 20:34 UTC, AtnesNess requested changes
Выглядит неплохо, но есть недочеты:
1) Не работает на мобилке
2) Вылетает ошибка в консоль при загрузке
3) Для блока затемнения используй general-shade
4) Юзер должен понимать куда он поставил точку, после повторного открытия карты
5) Убери лишние вендорные префиксы, ненужные коменты и желательно данные из парралеьных ПРов 116 и 115
6) Если будет возможность сделай так, чтобы блоки-дети гне знали о существовании блоков-родителей. Т.е не использовать document, а только пользоваться block
7) В код клиентского js пока особо не вдавался. Исправь пока предыдущие пункты

2017-05-12 20:34 UTC, AtnesNess commented on app.js
> +//  cachegoose(mongoose);
что это?

2017-05-12 20:34 UTC, AtnesNess commented on src/apps/quests/controllers.js
> +            return done(err);
я бы не стал включать изменения которые находятся сейчас в другом ПР

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.js
> +/* eslint no-alert:0 no-undef:0 */
зачем?

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.less
> +    -moz-border-radius: 14px 14px 0 0; /* Firefox */
вендорные префиксы не нужно добавлять, у нас для этого gulp

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +        popUpShadow.style.display = 'block';
у нас есть если что блок general-shade, он на мобилке себя норм ведет в отличае от этого =)

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +    if (e.target === popUpShadow) {
зачем эта проверка?

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +let popUpShadow = document.querySelector('.pop-up-shadow');
не очень хорошо когда вложенные блоки знают о том кто их в себя вложил.  Обратное возможно. когда родитель знает о своих детях. Ну да ладно пойдет

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +let btnSetGeolocation = document.querySelector('.set-geolocation');
тоже самое о родителях и детях

2017-05-12 20:34 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +    navigator.geolocation.getCurrentPosition(position => {
ну я думаю, у человека который редактирует должна быть возможность посмотреть куда он вообще ткнул. Т.е при открытии локации, если уже было что-то установлено нужно показывать ее, если ничего не установлено - указывать текущее местоположение.
И хорошо бы добавить кнопку, чтобы можно было перейти на текущее местоположение (как это сделано вк например)

2017-05-12 20:37 UTC, Sergey-Ubogov commented on app.js
> +//  cachegoose(mongoose);
это чтоб на локалке работало

2017-05-12 20:37 UTC, Sergey-Ubogov commented on src/blocks/create-quest-page/create-quest-page.js
> +/* eslint no-alert:0 no-undef:0 */
я сначало здесь кодил, потом перенес код, уберу )

2017-05-12 20:38 UTC, AtnesNess commented on app.js
> +//  cachegoose(mongoose);
для ПР это не нужно

2017-05-12 20:38 UTC, Sergey-Ubogov commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +    if (e.target === popUpShadow) {
когда жмешь на элемент, то он рекурсивно от ребенка до родителя срабатывает, т.е. если жмешь на карту, то она сскроется

2017-05-12 20:53 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +    if (e.target === popUpShadow) {
используй general-shade и z-index, тогда не нужно будет задумываться о родителях и всплытии

2017-05-13 11:02 UTC, AtnesNess requested changes
Не меняется адрес(строка) при просмотри позиций разных квестов

2017-05-13 11:02 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.js
> +let popUpShadow = document.querySelector('.general-shade');
block вместо document

2017-05-13 11:02 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/photos-list.less
> +.pop-up-shadow {
это можно убрать

2017-05-13 11:39 UTC, AtnesNess requested changes

2017-05-13 11:39 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/item/item.hbs
>  <input name="photo-block-{{index}}-photo" class="photo-link" {{bind-attr value="photo:photo"}}/>
может быть здесь нужен photo.url?

2017-05-13 12:09 UTC, Zeace approved these changes

2017-05-13 12:11 UTC, AtnesNess approved these changes
:+1:

2017-05-13 12:13 UTC, merged