Edit profile
urfu-2016/team4 pull request #135
Opened 2017-05-14 10:37 UTC by SvalovaNastya

2017-05-14 12:07 UTC, Sergey-Ubogov commented on src/blocks/profile-page/information/line/line.js
> +        deleteInfo({index: index_})
deleteInfo(index)

2017-05-14 12:07 UTC, Sergey-Ubogov commented on src/apps/profile/controllers.js
> +        let index = parseInt(req.body.index.index, 10);
let index = parseInt(req.body.index, 10);

2017-05-15 07:00 UTC, AtnesNess requested changes
TypeError: Cannot read property 'length' of undefined
для юзеров у кого нет инфы вообще

2017-05-17 15:19 UTC, AtnesNess requested changes

2017-05-17 15:19 UTC, AtnesNess commented on src/blocks/profile-page/information/line/line.hbs
> +    <div class="index hidden">{{this.index}}</div>
this это ключевое слово. Хз как это у тебя работает. Передавай ченить типа info

2017-05-17 15:19 UTC, AtnesNess commented on src/blocks/profile-page/information/information.hbs
> +    {{>line this=../this user=../user profile=../profile}}
я не понимаю зачем  this=../this
Ты хочешь передать строку инфы в шаблон. this это текущая инфа
пиши info=this и по info получай доступ к атрибутам внутри line

У меня из за этого вообще ничего не отображает в полях

2017-05-17 16:11 UTC, SvalovaNastya commented on src/blocks/profile-page/information/line/line.hbs
> +    <div class="index hidden">{{this.index}}</div>
работает, потому что я в this это и помещаю

2017-05-17 16:54 UTC, AtnesNess approved these changes

2017-05-17 17:05 UTC, Zeace approved these changes

2017-05-17 17:12 UTC, merged