сверстаны черновые варианты реиспользуемых блоков
urfu-2016/team4 pull request #16
Opened 2017-03-12 14:03 UTC by Zeace

2017-03-12 15:10 UTC, AtnesNess commented
А как же less

2017-03-12 17:51 UTC, SvalovaNastya commented on src/blocks/general/header/header.hbs
> +        <img src="quest-icon.png"/>
а почему это не ссылки?

2017-03-12 17:53 UTC, SvalovaNastya commented on src/blocks/general/filter/filter.hbs
> +var data = { params: [
Это можно вынести как раз во view-models. 

(но это неточно)

2017-03-12 17:55 UTC, SvalovaNastya commented on src/blocks/general/header/header.css
> +    border: 1px solid #dcdcdc;
Думаю, тут надо все константы вынести отдельно, чтоб потом менять было проще. 
Можно еще поразбираться, может, вообще в отдельный файл основной. Цвета-то точно будут повторяться. 
Цвета, шрифты, ..

2017-03-12 17:57 UTC, SvalovaNastya commented on src/blocks/general/header/header.css
> +header
а где вариант для телефонов? будет в следующем коммите?

2017-03-12 18:00 UTC, SvalovaNastya reviewed
Ну явно не хватает less. надо структурировать css, иначе это вырастет в огромный файлище. Лучше написать один большой файл для всего проекта с цветами и прочими постоянно используемыми штуками, а то дикое дублирование будет

2017-03-13 17:06 UTC, AtnesNess requested changes

2017-03-13 17:06 UTC, AtnesNess commented on src/blocks/general/quest-description/quest-description.less
> +.quest-description
https://github.com/urfu-2016/team4/pull/26 
почитай тут

2017-03-13 17:06 UTC, AtnesNess commented on src/blocks/general/quest-description/quest-description.hbs
> +    <img class="rating" src="like-icon.png">
вся статика идет по /static/img/...

2017-03-13 17:06 UTC, AtnesNess commented on src/blocks/general/create-button/create-button.hbs
> +<button class="create-button">Создать</button>
в дублирующих классах нету смысла. 
При build у тебя бдет конструкция:

```
<div class="create-button">
    <button class="create-button">Создать</button>
</div>
```

2017-03-13 17:06 UTC, AtnesNess commented on src/blocks/general/filter/filter.hbs
> +var data = { params: [
вообще это должно быть в контроллере как минимум.

2017-03-13 17:06 UTC, AtnesNess commented on src/blocks/general/save-button/save-button.hbs
> +<button class="create-button">Сохранить</button>
то же что и в create-button
Вообще по сути не вижу смысла разделять 2 одинаковых кнопки с разным текстом. Текст можно передавать в контекст компоненты

2017-03-21 01:36 UTC, closed without merging