настроила линт и тесты
urfu-2016/team4 pull request #20
Opened 2017-03-12 19:20 UTC by SvalovaNastya

2017-03-12 19:22 UTC, AtnesNess approved these changes
Круть, остался только деплой из CI

2017-03-12 19:22 UTC, Sergey-Ubogov approved these changes

2017-03-12 19:24 UTC, AtnesNess commented
Что-то пошло не так, CI зафейлил :D

2017-03-13 20:14 UTC, AtnesNess approved these changes
еще разобраться с css и html линтерами, но можно это сделать и в другом реквесте.
Еще нужно разобраться с табиками

2017-03-13 20:14 UTC, AtnesNess commented on app.js
> +	defaultLayout: 'main',
Вот он АД :D

2017-03-13 20:14 UTC, AtnesNess commented on src/controllers/routes.js
> +                /* eslint no-unused-vars: 0 */
тут нужно будет контроллеры вставить вместо функций

2017-03-15 08:15 UTC, TrefilovAnd commented on src/controllers/routes.js
> +                /* eslint no-unused-vars: 0 */
это просто как заглушки для примера стоят, чтоб видно было как работает это все

2017-03-15 08:15 UTC, TrefilovAnd approved these changes

2017-03-15 18:37 UTC, AtnesNess approved these changes
Надеюсь больше не будет tab Ада))

2017-03-19 15:00 UTC, AtnesNess commented
ВТФ:D А как же git pull --rebase upstream master

2017-03-21 20:45 UTC, AtnesNess requested changes

2017-03-21 20:45 UTC, AtnesNess commented on src/models/photo.js
> +/* eslint new-cap: 0 */
мм зачем?

2017-03-21 20:45 UTC, AtnesNess commented on app.js
> -    server: {
Линтинг 
   9:2  error  Expected indentation of 4 spaces but found 1 tab   indent
  10:2  error  Expected indentation of 4 spaces but found 1 tab   indent
  11:2  error  Expected indentation of 4 spaces but found 1 tab   indent
  12:2  error  Expected indentation of 4 spaces but found 1 tab   indent
  24:2  error  Expected indentation of 4 spaces but found 1 tab   indent
  25:3  error  Expected indentation of 4 spaces but found 2 tabs  indent
  26:4  error  Expected indentation of 4 spaces but found 3 tabs  indent
  27:3  error  Expected indentation of 0 spaces but found 2 tabs  indent
  28:2  error  Expected indentation of 0 spaces but found 1 tab   indent
  43:2  error  Expected indentation of 4 spaces but found 1 tab   indent

2017-03-21 20:45 UTC, AtnesNess commented on gulpfile.js
> +gulp.task('default', gulpSequence('lint', 'build', 'webserver', 'watch'));
354:75  error  Newline required at end of file but not found  eol-last

2017-03-21 20:45 UTC, AtnesNess commented on src/controllers/routes.js
> +        /* eslint no-unused-vars: 0 */
зачем?

2017-03-21 20:45 UTC, AtnesNess commented on src/controllers/routes.js
> +        /* eslint no-unused-vars: 0 */
и снова зачем :D

2017-03-21 20:45 UTC, AtnesNess commented on package.json
> +    "lint": "npm test & npm run lint:js"
где stylelint?

2017-03-21 20:45 UTC, AtnesNess commented on package.json
> +    "lint:js": "eslint src/**/*.js",
app.js и gulpfile.js  не подходят по маске

2017-03-21 20:45 UTC, AtnesNess commented on tests/base-test.js
> +assert.equal(1, 1);
если уж добавила пример теста то напиши правильно :D
```
describe('test-func', () => {
    it('1 equuals 1', () => {
        assert.equal(1,1);
    });
});
```

2017-03-22 05:31 UTC, SvalovaNastya commented on src/controllers/routes.js
> +        /* eslint no-unused-vars: 0 */
ну тут понятно зачем, у тебя неиспользуемые аргументы

2017-03-22 05:34 UTC, AtnesNess requested changes

2017-03-22 05:34 UTC, AtnesNess commented on src/controllers/routes.js
> +        /* eslint no-unused-vars: 0 */
как это, из req достается query, а в res вызывается render() или send()
```
          let value;
          if (req.query.value) {
              value = req.query.value;
         }
         Quest.find()
             .select('title author photos description -_id id likesCount rating')
             .populate('author', '-_id id name')
             .populate('photos', '-_id url')
             .exec()
             .then(data => {
                 data = questFilter.handle(value, data, req.query);
                 if (req.query.render === 'true') {
                     res.render('quest-list', {
                         quests: data,
                         layout: false
                     });
                 } else {
                     res.send(data);
                 }
             });
```

2017-03-22 06:12 UTC, AtnesNess commented
Ок. Не забудь потом пройтись по недоделкам типа тестов и коментов

2017-03-22 06:12 UTC, AtnesNess approved these changes

2017-03-22 06:14 UTC, merged