Documentation
urfu-2016/team4 pull request #22
Opened 2017-03-12 20:22 UTC by Sergey-Ubogov

Проверьте, может что забыл или добавить что нибудь

2017-03-13 10:16 UTC, AtnesNess commented on README.md
> +2. ( `git add <chacnged-file` )
очепятка

2017-03-13 10:18 UTC, AtnesNess commented
Неплохо описан workflow, но нужно еще добавить стек технологий, интерфейсы, основные фичи, описание build и src директорий

2017-03-15 08:16 UTC, TrefilovAnd approved these changes

2017-03-19 15:20 UTC, AtnesNess requested changes
В обзем хорошо, поправь только раздел категорий

2017-03-19 15:20 UTC, AtnesNess commented on README.md
> +# Директории
Тут бы не только принципы описать, но и структуру папок

2017-03-19 15:20 UTC, AtnesNess commented on README.md
> +&
Отступы поправь

2017-03-19 15:20 UTC, AtnesNess commented on README.md
> +<div class='<dir>'>
по `<dir>` не понятно что там будет написано

2017-03-19 15:51 UTC, AtnesNess approved these changes

2017-03-19 15:57 UTC, merged