profile page fix
urfu-2016/team4 pull request #43
Opened 2017-03-24 07:09 UTC by TrefilovAnd

Подправленная страница профиля

2017-03-24 13:01 UTC, AtnesNess requested changes
В целом неплохо, НО
1)не пройден линтинг( оч дофиг ошибок)
2) избавься от названий классов где используются имена компонент
если хочешь создать класс block-name-card
тогда создай отдельную компоненту в block-name как подпапку, т.к в итоге то и выйдет, но куда удобнее и читабельнее.
3)cards - это те же квесты, используй уже онаписаные, можешь их модифицировать. Если у них какое то разное поведение на разных страницах добавь модификаторов и передавай как аргумент модификатор в компонент

2017-03-24 13:01 UTC, AtnesNess commented on npm-debug.log
> +0 info it worked if it ends with ok
удали debug.log

2017-03-24 13:01 UTC, AtnesNess commented on src/blocks/profile-page/users-quests/users-quests.hbs
> +<div class="profile-page-users-quest-card">
.profile-page-users-quest-card 
не проще будет просто обозвать card, и в стилях обращаться к .card, переопределений считай нигде не будет, такой класс будет принадлежать только этому компоненту 
ну или я могу сделать элемент который будет парсится потом в такую штуку как у тебя
типа будешь указывать class="{{regPrefix 'card'}}" и скомпилится как profile-page-users-quest-card но могут возникнуть коллизии если ты создашь подпапку card, хотя поидее так и нужно сделать

2017-03-24 13:01 UTC, AtnesNess commented on src/blocks/profile-page/profile-page.hbs
> +<div class="profile-page-main-info-block">
лучше опускать  profile-page-main, пусть лучше будет просто info-block 
в стилях к нему будешь обращаться как .info-block
а скомпилится в profile-page-main info-block

2017-03-24 13:01 UTC, AtnesNess commented on src/blocks/profile-page/users-quests/users-quests.hbs
> +<div class="profile-page-users-quest-card">
А вообще card как я понял это quest. У нас же есть квесты в quest-list-item, используй их. Можешь и переделать их, важно чтобы они отображались на всех страницах в одном стили и были одним блоком, возможно подругому, но если только указать соответствующие модификаторы

2017-03-24 18:43 UTC, AtnesNess requested changes
Глянул с телефона, почти все супер 
1) не веде убрал profile-page 
2) статическую сортировку можно сразу пихать в контекст /profile, т.к нам не нужно изменять фильмы квестов при просмотре как это происходит в main-page . 
Поэтому избавься от js и используй просто компоненту

Линтинг и как визуально выглядит посмотрю завтра когда допилишь косячки

2017-03-24 18:43 UTC, AtnesNess commented on src/blocks/profile-page/profile-page.js
> +function filterQuests() {
Так у тебя статический фильтр, сделай его на бэкенде, и передай в res.render - quests, а в шаблоне пропиши {{>quest-list quests=quests}}

2017-03-24 18:43 UTC, AtnesNess commented on src/blocks/profile-page/profile-page.js
> +function filterQuests() {
Тут вообще не к чему is файл

2017-03-24 18:43 UTC, AtnesNess commented on src/blocks/profile-page/photo-block/photo-block.hbs
> +<img src="{{user.photoURL}}" alt="{{user.name}}" class="profile-page-photo"/>
Не убрал profile-page

2017-03-24 18:44 UTC, AtnesNess commented
Фильтры вместо фильмы😄

2017-03-24 19:13 UTC, SvalovaNastya approved these changes

2017-03-24 22:21 UTC, AtnesNess requested changes
Используй нативный фильтр монги и удали debug

2017-03-24 22:21 UTC, AtnesNess commented on src/controllers/routes.js
> +                        quests = questFilter.handle('name', quests, req.query);
Я в новом PR отказался от фильтра по всей коллекции. 
Сделай фильр сразу в find  на текущего юзера, тк пока авторизации нет поставь любого фиктивного и выводи только его квесты.

2017-03-25 16:37 UTC, AtnesNess reviewed
Убери дублирование, и можешь мержить))

2017-03-25 16:37 UTC, AtnesNess commented on src/controllers/routes.js
> +const User = require('../models/user');
Зачем 2 раза юзер ?

2017-03-25 16:38 UTC, TrefilovAnd commented on src/controllers/routes.js
> +const User = require('../models/user');
тот не мой был)) ща почищу

2017-03-25 16:43 UTC, merged