Пробная версия главной(в тч хэдера)
urfu-2016/team4 pull request #48
Opened 2017-03-26 09:23 UTC by Zeace

2017-03-26 09:30 UTC, TrefilovAnd commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center">{{quest.title}}</h4>
Вроде нельзя использовать h4, если на странице h3

2017-03-26 09:31 UTC, TrefilovAnd commented on src/blocks/main-page/main-page.hbs
>      <h2>О сервисе ФотоКвест</h2>
И тут тоже. h1 еще нет

2017-03-26 09:32 UTC, AtnesNess commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center">{{quest.title}}</h4>
разве? Помоему это не особо важно

2017-03-26 09:33 UTC, Zeace commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center">{{quest.title}}</h4>
тоже не слышал об этом

2017-03-26 09:34 UTC, TrefilovAnd commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center">{{quest.title}}</h4>
меня ментор со студентором пороли за это)) типа семантика. лучше в стилях размер регулировать

2017-03-26 09:39 UTC, Zeace commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center">{{quest.title}}</h4>
ну ладно, не сильно велика проблема)

2017-03-26 09:44 UTC, AtnesNess commented
Супер гуд!
1)Поправить страницу профиля
2) Сортировка -> Поиск (в центр)
3) Лоадер по смене фильтров

2017-03-26 09:45 UTC, AtnesNess requested changes
Супер гуд!
1)Поправить страницу профиля
2) Сортировка -> Поиск (в центр)
3) Лоадер по смене фильтров

2017-03-26 14:15 UTC, AtnesNess reviewed
Топчик!
только линт поправь
src/blocks/profile-page/profile-page.less
 3:19  ✖  Expected single space after ":" with a single-line declaration   declaration-colon-space-after
 9:1   ✖  Expected empty line before rule                                  rule-empty-line-before

2017-03-26 14:28 UTC, AtnesNess commented
Ой, чет сразу не заметил
{{>general-header}} должен быть в layout
зачем его пихать то во все блоки :D

2017-03-26 15:23 UTC, AtnesNess approved these changes

2017-03-26 15:25 UTC, AtnesNess approved these changes

2017-03-27 18:12 UTC, TrefilovAnd approved these changes
Всю мою верстку поменял))

2017-03-27 19:04 UTC, Sergey-Ubogov approved these changes

2017-03-28 02:03 UTC, merged