Create quest page start
urfu-2016/team4 pull request #59
Opened 2017-04-02 16:02 UTC by TrefilovAnd

Просто собрал структуру страницы без стилей и функционала

2017-04-02 18:07 UTC, AtnesNess requested changes
Для PR надо как минимум либо дизайн либо функционал

2017-04-02 18:07 UTC, AtnesNess commented on src/blocks/create-quest-page/quest/title/title.hbs
> +<input type="text" name="questTitle">
lint  2:1  error  void element should close itself  tag-self-close

2017-04-02 18:07 UTC, AtnesNess commented on src/blocks/create-quest-page/photos-list/item/photo/photo.hbs
> +<img src="http://re-actor.net/uploads/posts/2012-07/1342811847_8.jpg" alt="myPhoto" height="250px">
lint  1:1  error  void element should close itself  tag-self-close

2017-04-03 18:18 UTC, AtnesNess approved these changes
В общем гуд, но не хватает установки локации, и есть пару замечаний. Смотри по желанию, можно и в отдельный PR

2017-04-03 18:18 UTC, AtnesNess commented on src/blocks/create-quest-page/publish-button/public-button.hbs
> +{{> general-radio-button text='Опубликовать'}}
почему радио?

2017-04-03 18:18 UTC, AtnesNess commented on src/blocks/create-quest-page/quest/description/description.hbs
> +<textarea name="questDescription" class="form-control" rows="5"></textarea>
я бы ее сделал чтобы высота ее была такой, чтобы снизу была по уровню фотки)

2017-04-04 06:43 UTC, TrefilovAnd commented on src/blocks/create-quest-page/quest/description/description.hbs
> +<textarea name="questDescription" class="form-control" rows="5"></textarea>
это описание самого квеста, а не фоотки. Но я тебя понял

2017-04-04 15:05 UTC, AtnesNess approved these changes
Огонь, но все же не хватает карты для указания местоположения.

2017-04-04 15:55 UTC, AtnesNess approved these changes

2017-04-04 19:34 UTC, Sergey-Ubogov approved these changes

2017-04-05 06:44 UTC, merged