Description page
urfu-2016/team4 pull request #60
Opened 2017-04-02 18:51 UTC by Sergey-Ubogov

2017-04-02 19:01 UTC, AtnesNess reviewed
По макету все круто сделано, но чет когда добавишь дофига фоток, то не оч выходит..
И еще не понятен момент с начать квест - продолжить квест. Его же нельзя начать дважды :D Вобщем надобы вообще переосмыслить эту страницу

2017-04-02 19:01 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.hbs
> +<!--styles:-->
к чему этот коммент?

2017-04-02 19:01 UTC, AtnesNess commented on src/blocks/quest-list/item/item.hbs
> +<h4 class="text-center"><a href="/quest/{{quest.id}}">{{quest.title}}</a></h4>
я думаю лучше сделать при нжатии на весь блок - переход

2017-04-03 07:44 UTC, AtnesNess requested changes
Уже намного лучше, но пары штрихов не хватает.
и исправь индусский код в контроллере :D

2017-04-03 07:44 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.hbs
> +	{{>quest-description-page-photo-block}}
Там намного лучше, но лучше бы сделать красивый слайдер, который потихоньку сам двигается, без скролбара снизу.

2017-04-03 07:44 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.hbs
> +	{{>general-button text='Начать или продолжить квест' style='primary'}}
1) Тут должно быть либо начать либо продолжить, нужно анализировать участвовал юзер в этом квесте уже или нет. 
2) Если юзер не авторизован  - выдавать сообщение о том, что вы не можете принять участие пока не зарегаетесь

2017-04-03 07:44 UTC, AtnesNess commented on src/controllers/routes.js
> +        let questId = req.url.split('/').slice(-1)[0];
Лол)) 
используй req.params.id

2017-04-03 11:41 UTC, Sergey-Ubogov commented
http://caniuse.com/#search=-webkit-scrollbar

2017-04-03 11:43 UTC, AtnesNess requested changes

2017-04-03 11:43 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.js
> +let photoBlock = document.getElementsByClassName('quest-description-page-photo-block')[0];
используй querySelector

2017-04-03 11:43 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.js
> +function shiftRight() {
Оч странная реализация)
Я имел ввиду, что пусть они потихоньку сами перемещаются (аля слайдер), но при нажатии влево вправо, должно быть смещение на несколько квестов вправо-влево (столько сколько помещается на экран)
Типа как здесь https://rawgit.com/AtnesNess/markup-task-6/master/index.html , но еще чтоб сами потихоньку плыли

2017-04-03 11:43 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.hbs
> +        <div><img src="http://i.imgur.com/Btb1iUT.png" alt="left arrow" class="left-arrow"
Стрелочки ужасны, лучше через css сделай.

2017-04-03 11:46 UTC, AtnesNess requested changes

2017-04-03 11:46 UTC, AtnesNess commented on src/blocks/quest-description-page/photo-block/photo-block.less
> +	display: none;
это можно сделать не только таким методом. 
Почитац про overflow: hidden

2017-04-03 16:34 UTC, Sergey-Ubogov commented
инерцию сделаю позже

2017-04-03 18:12 UTC, AtnesNess requested changes

2017-04-03 18:12 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.js
> +const photoBlock = document.querySelector('.quest-description-page-photo-block');
https://lisa.convertio.me/p/XV_qfSlKWTyxNPm3SPV02w/cadd549a70744ceb073bc46f6597e923/out-1.gif
Что то пошло не так

2017-04-04 06:50 UTC, TrefilovAnd approved these changes

2017-04-04 15:16 UTC, AtnesNess reviewed
Все супер. добавь только курсоры при наведении и нажатии. pointer, move и будет aprove)

2017-04-04 15:16 UTC, AtnesNess commented on README.md
> -## 1. Подготовка к разработке
это в отдельный PR

2017-04-08 07:56 UTC, AtnesNess approved these changes
Шик!
Жаль только после ударения об стенку не сохраняется скорость :D Но это мелочь)
А еще это не работает на мобилке, но это потом)

2017-04-08 08:12 UTC, merged