свертано: страница квесты и добавлена оболочка под редактирование инф в профиле
urfu-2016/team4 pull request #62
Opened 2017-04-04 05:17 UTC by Zeace

само описание квестов на их странице отдельной веткой сделаю

2017-04-04 06:48 UTC, TrefilovAnd commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +    </label>
может лучше вынести как отдельный элемент и просто передавать туда контекст? просто 3 раза повторяется таб

2017-04-04 15:25 UTC, AtnesNess requested changes
Задумка крутая, но на PR пока не тянет, нужен контент под табиками

2017-04-04 15:25 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +    </label>
Согласен

2017-04-08 07:51 UTC, AtnesNess approved these changes
Все гуд) 
Есть пара замечаний, можешь исправить, можешь не исправлять) 
Не оч понял зачем quest-description тут, но это если че позже обсудим)

2017-04-08 07:51 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +{{> my-quests-page-tabs-tab name="tabs" id="tab-first" checked="checked" for="tab-first" text="Активные квесты"}}
For уже не нужен

2017-04-08 07:51 UTC, AtnesNess commented on src/blocks/variables.less
> +@tab-border-bottom-yellow: 4px solid @yellowColor;
По хорошему цвета бы не задавать в имени, т.к если захотим сменить цветовую гамму, то будет другой цвет а имя .\*yellow.\* 
Не особо важное замечание, но так на будущее

2017-04-08 07:51 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +
Урезал бы переносы до 1)

2017-04-08 07:51 UTC, AtnesNess commented on src/blocks/my-quests-page/my-quests-page.hbs
> +{{> general-quest-description questname='fff' description='dddd'}}
Я бы вместо general-description просто выдавал бы список как на главной, а то помоему смысл в просмотре квеста уже отпадает :D Ну типа итак уже все описание есть) 
Ну я когда сделаю функционал на табики, посмотришь)

2017-04-08 08:43 UTC, Sergey-Ubogov approved these changes

2017-04-08 15:02 UTC, TrefilovAnd approved these changes

2017-04-08 20:24 UTC, AtnesNess requested changes

2017-04-08 20:24 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tab/tab.less
> +& label p {
тут можешь опускать &

2017-04-08 20:24 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tab/tab.less
> +& [id^="tab"]:checked + label {
типа нужно указывать конкретно чтоб id начинался с tab?

2017-04-08 20:24 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tab/tab.hbs
> +    {{bind-attr checked="checked:checked"}}
тут бы еще value добавить

2017-04-08 20:24 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +{{> my-quests-page-tabs-tab name="tabs" id="tab-second" for="tab-second" text="Завершенные квесты"}}
Вообще лучше перенести это все в my-quests-page
Типа сделать как то так
<div class="tabs">
    {{> my-quests-page-tab name="tabs" id="activeQuests"  checked="checked" text="Активные квесты"}}
    {{> my-quests-page-tab name="tabs" id="finishedQuests" text="Завершенные квесты"}}
    {{> my-quests-page-tab name="tabs" id="createdQuests" text="Cозданные квесты"}}
</div>
<div class="quests-block">

</div>

2017-04-08 20:24 UTC, AtnesNess commented on src/blocks/my-quests-page/tabs/tabs.hbs
> +{{> my-quests-page-tabs-tab name="tabs" id="tab-first" checked="checked" for="tab-first" text="Активные квесты"}}
А по хорошему вообще бы от id избавиться, но я не знаю возможно ли :D

2017-04-08 20:25 UTC, AtnesNess requested changes
И еще линт!) 
Я щас PR сделал чтобы он проверялся еще на ревьюинге. Щас чет не работало это и наговнокодили :D

2017-04-09 08:20 UTC, merged