Documentation
urfu-2016/team4 pull request #63
Opened 2017-04-08 10:54 UTC by Sergey-Ubogov

2017-04-08 19:13 UTC, AtnesNess requested changes

2017-04-08 19:13 UTC, AtnesNess commented on src/blocks/quest-description-page/quest-description-page.js
> -﻿/* eslint no-unused-vars: 'off' */
Здесь не место))

2017-04-09 11:49 UTC, Sergey-Ubogov commented on src/blocks/quest-description-page/quest-description-page.js
> -﻿/* eslint no-unused-vars: 'off' */
ок вернул как было

2017-04-09 12:33 UTC, AtnesNess approved these changes

2017-04-11 17:26 UTC, Zeace approved these changes

2017-04-11 17:29 UTC, merged