верстка страницы с фотографиями квестов
urfu-2016/team4 pull request #69
Opened 2017-04-12 15:16 UTC by Sergey-Ubogov

2017-04-12 15:17 UTC, Sergey-Ubogov commented on src/blocks/general/login-form/login-form.less
> -    position: absolute;
если у страницы есть скролл то форма логина была далеко внизу

2017-04-13 06:03 UTC, Zeace requested changes
с телефона не получается зайти в фотографии первого квеста (их там много и они автоскролятся)
остальное ок

2017-04-15 12:53 UTC, Zeace approved these changes

2017-04-16 07:03 UTC, TrefilovAnd approved these changes

2017-04-16 07:04 UTC, merged