функционал добавления файлов
urfu-2016/team4 pull request #81
Opened 2017-04-16 16:46 UTC by Sergey-Ubogov

modified:   .gitignore
	modified:   gulpfile.js
	modified:   package.json
	modified:   src/blocks/create-quest-page/add-photo-button/add-photo-button.hbs
	modified:   src/blocks/create-quest-page/create-quest-page.hbs
	modified:   src/blocks/profile-page/photo-block/photo-block.hbs
	modified:   src/blocks/profile-page/photo-block/photo-block.less
	new file:   src/controllers/cloudinary.js
	modified:   src/controllers/routes.js

2017-04-17 13:37 UTC, TrefilovAnd commented on src/blocks/create-quest-page/create-quest-page.hbs
> +<form method="post" enctype="multipart/form-data">
Мы же решили, что каждая фотография будет сразу же добавляться. Надо будет js файл подключить и событие 'change' обрабатывать на каждой фотке.

+ надо еще раз убедиться у ребят, что коменты нам не нужны к фотографиям

2017-04-19 07:48 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.hbs
> +<form method="post" enctype="multipart/form-data">
Коменты к фоткам будут в в дальнейшем. Описания не будет

2017-04-19 08:07 UTC, AtnesNess requested changes
Не понял почему изменения с других PR здесь ну да ладно. 

Есть косяк который нужно исправить при згрузке фотки

2017-04-19 08:07 UTC, AtnesNess commented on src/controllers/routes.js
> -            photos: [
раз пока загрузка фоток не работает, оставь как было, чтоб хотябы была видна верстка

2017-04-19 08:07 UTC, AtnesNess commented on src/controllers/routes.js
> +        cloudinary.savePhoto(req.file.path, result => {
при загрузке аватара выводится (node:19470) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Разберись

2017-04-19 16:14 UTC, AtnesNess requested changes

2017-04-19 16:14 UTC, AtnesNess commented on app.js
> +app.use(jsonParser);
это нужно делать в midlewares

2017-04-19 16:14 UTC, AtnesNess commented on src/controllers/routes.js
> +        function decodeBase64Image(dataString) {
не оч понял, это нам зачем?

2017-04-19 16:14 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.hbs
> +            <input type="file" name="addPhoto" onchange="previewFile()"
читай PR'ы внимательнее
https://github.com/urfu-2016/team4/pull/79
onchange не сработает
избавься от document (сейчас можно искать относительно блока в котором ты пишешь (block))

2017-04-19 16:14 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.js
> +        let xhr = new XMLHttpRequest();
используй fetch

2017-04-19 16:14 UTC, AtnesNess commented on src/blocks/create-quest-page/create-quest-page.js
> +function previewFile() {
вообще какая то сложная логика, лучше сделай роут в который ты можешь запостить картинку а он тебе выплюнет отрендеренный photo-list-item

2017-05-06 11:40 UTC, closed without merging